name: Build Windows EXE

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build-windows-exe:
    runs-on: windows-latest  # 使用 Windows 运行器
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl pyinstaller
    
    - name: Build EXE file
      run: |
        pyinstaller --onefile --console --name "Excel对比分析工具" excel_analyzer.py
        dir dist\  # 列出生成的文件
    
    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Excel对比分析工具
        path: dist/Excel对比分析工具.exe
        retention-days: 30

    - name: Create release (optional)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/Excel对比分析工具.exe
