name: Build and Release

on:
  push:
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install pandas openpyxl pyinstaller
    
    - name: Build EXE
      run: |
        pyinstaller --onefile --console --name "ExcelAnalyzer" excel_analyzer.py
    
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: "v${{ github.run_number }}"
        name: "Excel分析工具 v${{ github.run_number }}"
        body: "Excel对比字段分析工具 Windows 版本"
        artifacts: "dist/ExcelAnalyzer.exe"
        token: ${{ secrets.GITHUB_TOKEN }}
